name       : haskell-aeson
version    : 1.0.2.1
release    : 1
source     :
    - https://hackage.haskell.org/package/aeson-1.0.2.1/aeson-1.0.2.1.tar.gz : e0a66fba0a9996063d0e241b0b868c6271b6aeb457821a78bfcaac5d84c89066
license    : BSD-3-Clause
component  : programming
summary    : aeson is a fast Haskell library for working with JSON data
description: |
    aeson is a fast Haskell library for working with JSON data
builddeps  :
    - ghc
    - haskell-attoparsec
    - haskell-base-compat
    - haskell-dlist
    - haskell-hashable
    - haskell-scientific
    - haskell-tagged
    - haskell-text
    - haskell-time-locale-compat
    - haskell-unordered-containers
    - haskell-vector
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 aeson-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/aeson-$version.conf