name       : haskell-aeson
version    : 1.3.1.1
release    : 4
source     :
    - https://hackage.haskell.org/package/aeson-1.3.1.1/aeson-1.3.1.1.tar.gz : 843f302f8186c1ee6e0d9c0630588e4c7fc0f41763333a2d0d4b6f07087a31c4
license    : BSD-3-Clause
component  : programming.haskell
summary    : aeson is a fast Haskell library for working with JSON data
description: |
    aeson is a fast Haskell library for working with JSON data
builddeps  :
    - ghc
    - haskell-attoparsec
    - haskell-base-compat
    - haskell-cabal-install
    - haskell-dlist
    - haskell-hashable
    - haskell-scientific
    - haskell-tagged
    - haskell-text
    - haskell-th-abstraction
    - haskell-time-locale-compat
    - haskell-unordered-containers
    - haskell-uuid-types
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
