name       : haskell-aeson
version    : 1.5.2.0
release    : 5
source     :
    - https://hackage.haskell.org/package/aeson-1.5.2.0/aeson-1.5.2.0.tar.gz : cd3598924ffdafb5222202af73aaa59bc5d4ac8cf590e06f67b5a6a3751b932b
license    : BSD-3-Clause
component  : programming.haskell
summary    : aeson is a fast Haskell library for working with JSON data
description: |
    aeson is a fast Haskell library for working with JSON data
builddeps  :
    - haskell-attoparsec-devel
    - haskell-base-compat-batteries-devel
    - haskell-cabal-install
    - haskell-dlist-devel
    - haskell-tagged-devel
    - haskell-th-abstraction-devel
    - haskell-these-devel
    - haskell-time-compat-devel
    - haskell-unordered-containers-devel
    - haskell-uuid-types-devel
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-attoparsec-devel
        - haskell-base-compat-batteries-devel
        - haskell-dlist-devel
        - haskell-tagged-devel
        - haskell-th-abstraction-devel
        - haskell-these-devel
        - haskell-time-compat-devel
        - haskell-unordered-containers-devel
        - haskell-uuid-types-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
