name       : haskell-aeson
version    : 1.0.2.1
release    : 3
source     :
    - https://hackage.haskell.org/package/aeson-1.0.2.1/aeson-1.0.2.1.tar.gz : e0a66fba0a9996063d0e241b0b868c6271b6aeb457821a78bfcaac5d84c89066
license    : BSD-3-Clause
component  : programming.haskell
summary    : aeson is a fast Haskell library for working with JSON data
description: |
    aeson is a fast Haskell library for working with JSON data
builddeps  :
    - ghc
    - haskell-attoparsec
    - haskell-base-compat
    - haskell-cabal-install
    - haskell-dlist
    - haskell-hashable
    - haskell-scientific
    - haskell-tagged
    - haskell-text
    - haskell-time-locale-compat
    - haskell-unordered-containers
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
